### ISSUE TITLE
Confirm alternative web driver support

### ISSUE THREAD

**Issue by lzinga** [lzinga/AutoWeb#6]
Right now AutoWeb uses msedgedriver as default. Add tests to verify it works with other web drivers like Firefox or Chrome.

**Comment by dbettin** [comment]
This is perfect timing. Would love to see support for chrome.

**Comment by lzinga** [comment]
> This is perfect timing. Would love to see support for chrome.

I have some changes I am working on now for this. Running into a few issues but hopefully should have something soon.

**Comment by lzinga** [comment]
@dbettin I checked in the changes for alternative browser support. It still defaults to use msedgedriver.exe but you can now call something like the following - 

```csharp
new PageCollection(options => {
    options.Browser<ChromeBrowser>("chromedriver.exe")
});
```

you can also configure the arguments for the browser, for example `--headless` to hide the browser during execution. The readme has been updated as well with some of this new information.
